// Error code enum for API errors
 
export enum ApiErrorCode {
  // Validation Errors - Auth
  EMAIL_REQUIRED = "EMAIL_REQUIRED",
  EMAIL_INVALID = "EMAIL_INVALID",
  PASSWORD_REQUIRED = "PASSWORD_REQUIRED",
  PASSWORD_MIN_LENGTH = "PASSWORD_MIN_LENGTH",
  CURRENT_PASSWORD_REQUIRED = "CURRENT_PASSWORD_REQUIRED",
  NEW_PASSWORD_REQUIRED = "NEW_PASSWORD_REQUIRED",
  NEW_PASSWORD_MIN_LENGTH = "NEW_PASSWORD_MIN_LENGTH",
  REFRESH_TOKEN_REQUIRED = "REFRESH_TOKEN_REQUIRED",
  ROLE_REQUIRED = "ROLE_REQUIRED",
  ROLE_INVALID = "ROLE_INVALID",

  // Validation Errors - User
  FIRST_NAME_REQUIRED = "FIRST_NAME_REQUIRED",
  FIRST_NAME_MIN_LENGTH = "FIRST_NAME_MIN_LENGTH",
  FIRST_NAME_MAX_LENGTH = "FIRST_NAME_MAX_LENGTH",
  LAST_NAME_REQUIRED = "LAST_NAME_REQUIRED",
  LAST_NAME_MIN_LENGTH = "LAST_NAME_MIN_LENGTH",
  LAST_NAME_MAX_LENGTH = "LAST_NAME_MAX_LENGTH",
  PHONE_NUMBER_REQUIRED = "PHONE_NUMBER_REQUIRED",
  PHONE_NUMBER_MIN_LENGTH = "PHONE_NUMBER_MIN_LENGTH",
  PHONE_NUMBER_MAX_LENGTH = "PHONE_NUMBER_MAX_LENGTH",
  SCHOOL_ID_REQUIRED = "SCHOOL_ID_REQUIRED",
  SCHOOL_ID_INVALID_UUID = "SCHOOL_ID_INVALID_UUID",
  SCHOOL_ID_NOT_ASSOCIATED = "SCHOOL_ID_NOT_ASSOCIATED",

  // Validation Errors - School
  SCHOOL_NAME_REQUIRED = "SCHOOL_NAME_REQUIRED",
  SCHOOL_NAME_MIN_LENGTH = "SCHOOL_NAME_MIN_LENGTH",
  SCHOOL_NAME_MAX_LENGTH = "SCHOOL_NAME_MAX_LENGTH",
  SLUG_MIN_LENGTH = "SLUG_MIN_LENGTH",
  SLUG_MAX_LENGTH = "SLUG_MAX_LENGTH",
  SLUG_INVALID = "SLUG_INVALID",
  SLUG_INVALID_FORMAT = "SLUG_INVALID_FORMAT",
  DISCIPLINES_REQUIRED = "DISCIPLINES_REQUIRED",
  DISCIPLINES_MIN_SELECTION = "DISCIPLINES_MIN_SELECTION",
  OPEN_HOURS_INVALID_FORMAT = "OPEN_HOURS_INVALID_FORMAT",
  URL_INVALID = "URL_INVALID",
  ADDRESS_MAX_LENGTH = "ADDRESS_MAX_LENGTH",
  SPOT_NAME_MAX_LENGTH = "SPOT_NAME_MAX_LENGTH",

  // Validation Errors - Instructor
  SPECIALTIES_REQUIRED = "SPECIALTIES_REQUIRED",
  SPECIALTIES_MIN_SELECTION = "SPECIALTIES_MIN_SELECTION",
  LANGUAGES_REQUIRED = "LANGUAGES_REQUIRED",
  LANGUAGES_MIN_SELECTION = "LANGUAGES_MIN_SELECTION",
  AVATAR_INVALID_URL = "AVATAR_INVALID_URL",
  CERTIFICATION_MIN_LENGTH = "CERTIFICATION_MIN_LENGTH",
  CERTIFICATION_MAX_LENGTH = "CERTIFICATION_MAX_LENGTH",
  LANGUAGE_MIN_LENGTH = "LANGUAGE_MIN_LENGTH",
  LANGUAGE_MAX_LENGTH = "LANGUAGE_MAX_LENGTH",
  HOURLY_RATE_MIN = "HOURLY_RATE_MIN",
  HOURLY_RATE_INVALID = "HOURLY_RATE_INVALID",
  COMMISSION_RATE_MIN = "COMMISSION_RATE_MIN",
  COMMISSION_RATE_MAX = "COMMISSION_RATE_MAX",
  COMMISSION_RATE_INVALID = "COMMISSION_RATE_INVALID",
  NOTES_MAX_LENGTH = "NOTES_MAX_LENGTH",

  // Validation Errors - Student
  STUDENT_LEVEL_REQUIRED = "STUDENT_LEVEL_REQUIRED",
  STUDENT_LEVEL_ID_INVALID_UUID = "STUDENT_LEVEL_ID_INVALID_UUID",
  SKILL_LEVEL_REQUIRED = "SKILL_LEVEL_REQUIRED",
  SKILL_LEVEL_MIN_LENGTH = "SKILL_LEVEL_MIN_LENGTH",
  SKILL_LEVEL_MAX_LENGTH = "SKILL_LEVEL_MAX_LENGTH",
  SKILL_LEVEL_EMPTY = "SKILL_LEVEL_EMPTY",
  PREFERRED_DISCIPLINES_REQUIRED = "PREFERRED_DISCIPLINES_REQUIRED",
  PREFERRED_DISCIPLINES_MIN_SELECTION = "PREFERRED_DISCIPLINES_MIN_SELECTION",
  DATE_OF_BIRTH_INVALID = "DATE_OF_BIRTH_INVALID",
  EMERGENCY_CONTACT_MAX_LENGTH = "EMERGENCY_CONTACT_MAX_LENGTH",
  EMERGENCY_PHONE_MIN_LENGTH = "EMERGENCY_PHONE_MIN_LENGTH",
  EMERGENCY_PHONE_MAX_LENGTH = "EMERGENCY_PHONE_MAX_LENGTH",
  MEDICAL_CONDITIONS_MAX_LENGTH = "MEDICAL_CONDITIONS_MAX_LENGTH",
  WHATSAPP_NUMBER_REQUIRED = "WHATSAPP_NUMBER_REQUIRED",
  WHATSAPP_NUMBER_MIN_LENGTH = "WHATSAPP_NUMBER_MIN_LENGTH",
  WHATSAPP_NUMBER_MAX_LENGTH = "WHATSAPP_NUMBER_MAX_LENGTH",
  CAN_SWIM_REQUIRED = "CAN_SWIM_REQUIRED",
  CAN_SWIM_INVALID = "CAN_SWIM_INVALID",
  NATIONALITY_MAX_LENGTH = "NATIONALITY_MAX_LENGTH",
  WEIGHT_INVALID = "WEIGHT_INVALID",
  WEIGHT_MIN = "WEIGHT_MIN",
  WEIGHT_MAX = "WEIGHT_MAX",
  HEIGHT_INVALID = "HEIGHT_INVALID",
  HEIGHT_MIN = "HEIGHT_MIN",
  HEIGHT_MAX = "HEIGHT_MAX",
  PRIMARY_SPORT_INVALID = "PRIMARY_SPORT_INVALID",
  RIDING_BACKGROUND_MAX_LENGTH = "RIDING_BACKGROUND_MAX_LENGTH",
  PREFERRED_LANGUAGE_MAX_LENGTH = "PREFERRED_LANGUAGE_MAX_LENGTH",

  // Validation Errors - Discipline
  NAME_REQUIRED = "NAME_REQUIRED",
  NAME_MIN_LENGTH = "NAME_MIN_LENGTH",
  NAME_MAX_LENGTH = "NAME_MAX_LENGTH",
  DISPLAY_NAME_REQUIRED = "DISPLAY_NAME_REQUIRED",
  DISPLAY_NAME_MIN_LENGTH = "DISPLAY_NAME_MIN_LENGTH",
  DISPLAY_NAME_MAX_LENGTH = "DISPLAY_NAME_MAX_LENGTH",
  DESCRIPTION_MAX_LENGTH = "DESCRIPTION_MAX_LENGTH",
  ICON_MAX_LENGTH = "ICON_MAX_LENGTH",
  COLOR_INVALID_HEX = "COLOR_INVALID_HEX",
  SORT_ORDER_INVALID = "SORT_ORDER_INVALID",
  SORT_ORDER_MIN = "SORT_ORDER_MIN",
  ORDER_POSITION_INVALID = "ORDER_POSITION_INVALID",
  ORDER_POSITION_MIN = "ORDER_POSITION_MIN",

  // Validation Errors - Student Level
  STUDENT_LEVEL_NAME_REQUIRED = "STUDENT_LEVEL_NAME_REQUIRED",
  STUDENT_LEVEL_NAME_MIN_LENGTH = "STUDENT_LEVEL_NAME_MIN_LENGTH",
  STUDENT_LEVEL_NAME_MAX_LENGTH = "STUDENT_LEVEL_NAME_MAX_LENGTH",

  // Validation Errors - Product Category
  CATEGORY_NAME_REQUIRED = "CATEGORY_NAME_REQUIRED",
  CATEGORY_NAME_MIN_LENGTH = "CATEGORY_NAME_MIN_LENGTH",
  CATEGORY_NAME_MAX_LENGTH = "CATEGORY_NAME_MAX_LENGTH",
  DEFAULT_MAX_PARTICIPANTS_INVALID = "DEFAULT_MAX_PARTICIPANTS_INVALID",
  DEFAULT_MAX_PARTICIPANTS_MIN = "DEFAULT_MAX_PARTICIPANTS_MIN",

  // Validation Errors - Product
  TITLE_REQUIRED = "TITLE_REQUIRED",
  TITLE_MIN_LENGTH = "TITLE_MIN_LENGTH",
  TITLE_MAX_LENGTH = "TITLE_MAX_LENGTH",
  CATEGORY_ID_REQUIRED = "CATEGORY_ID_REQUIRED",
  CATEGORY_ID_INVALID_UUID = "CATEGORY_ID_INVALID_UUID",
  DISCIPLINE_ID_INVALID_UUID = "DISCIPLINE_ID_INVALID_UUID",
  PRICE_REQUIRED = "PRICE_REQUIRED",
  PRICE_MIN = "PRICE_MIN",
  PRICE_INVALID = "PRICE_INVALID",
  DURATION_INVALID = "DURATION_INVALID",
  DURATION_MIN = "DURATION_MIN",
  MAX_PARTICIPANTS_INVALID = "MAX_PARTICIPANTS_INVALID",
  MAX_PARTICIPANTS_MIN = "MAX_PARTICIPANTS_MIN",
  PRICE_TYPE_INVALID = "PRICE_TYPE_INVALID",
  PRODUCT_DESCRIPTION_MAX_LENGTH = "PRODUCT_DESCRIPTION_MAX_LENGTH",
  PRODUCT_NOTE_MAX_LENGTH = "PRODUCT_NOTE_MAX_LENGTH",

  // Validation Errors - Pagination & Search
  PAGE_INVALID = "PAGE_INVALID",
  PAGE_MIN = "PAGE_MIN",
  LIMIT_INVALID = "LIMIT_INVALID",
  LIMIT_MIN = "LIMIT_MIN",
  LIMIT_MAX = "LIMIT_MAX",
  SEARCH_QUERY_REQUIRED = "SEARCH_QUERY_REQUIRED",
  SEARCH_QUERY_MIN_LENGTH = "SEARCH_QUERY_MIN_LENGTH",
  SEARCH_QUERY_MAX_LENGTH = "SEARCH_QUERY_MAX_LENGTH",

  // Business Logic Errors
  INSTRUCTOR_LESSON_CONFLICT = "INSTRUCTOR_LESSON_CONFLICT",
  INSTRUCTOR_ALREADY_HAS_LESSON = "INSTRUCTOR_ALREADY_HAS_LESSON",
  SCHOOL_CLOSED_DATE = "SCHOOL_CLOSED_DATE",
  SCHOOL_CLOSED_CANNOT_CREATE = "SCHOOL_CLOSED_CANNOT_CREATE",
  INSTRUCTOR_NOT_AVAILABLE = "INSTRUCTOR_NOT_AVAILABLE",
  LESSON_TIME_OVERLAP = "LESSON_TIME_OVERLAP",
  INVALID_STUDENT_ID = "INVALID_STUDENT_ID",
  SCHOOL_SLUG_EXISTS = "SCHOOL_SLUG_EXISTS",
  BOOKING_STUDENTS_SKILL_LEVEL_REQUIRED = "BOOKING_STUDENTS_SKILL_LEVEL_REQUIRED",
  NO_AVAILABLE_BOOKED_HOURS = "NO_AVAILABLE_BOOKED_HOURS",
  INSTRUCTOR_EDIT_NOT_AUTHORIZED = "INSTRUCTOR_EDIT_NOT_AUTHORIZED",

  // Resource Errors
  LESSON_ID_REQUIRED = "LESSON_ID_REQUIRED",
  DISCIPLINE_ID_REQUIRED = "DISCIPLINE_ID_REQUIRED",
  USER_ID_REQUIRED = "USER_ID_REQUIRED",
  SCHOOL_NOT_FOUND = "SCHOOL_NOT_FOUND",
  LESSON_NOT_FOUND = "LESSON_NOT_FOUND",
  STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND",
  DISCIPLINE_NOT_FOUND = "DISCIPLINE_NOT_FOUND",
  STUDENT_LEVEL_NOT_FOUND = "STUDENT_LEVEL_NOT_FOUND",
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  PRODUCT_CATEGORY_NOT_FOUND = "PRODUCT_CATEGORY_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",

  // Authorization Errors
  AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED",
  ACCESS_DENIED = "ACCESS_DENIED",
  USER_NOT_ASSOCIATED_SCHOOL = "USER_NOT_ASSOCIATED_SCHOOL",
  USER_NOT_AUTHENTICATED = "USER_NOT_AUTHENTICATED",

  // System Errors
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  DATE_QUERY_REQUIRED = "DATE_QUERY_REQUIRED",
}

export const ERROR_MESSAGE_TO_CODE: Record<string, ApiErrorCode> = {
  // Auth Validation
  "Email is required": ApiErrorCode.EMAIL_REQUIRED,
  "Please provide a valid email address": ApiErrorCode.EMAIL_INVALID,
  "Password is required": ApiErrorCode.PASSWORD_REQUIRED,
  "Password must be at least 6 characters long": ApiErrorCode.PASSWORD_MIN_LENGTH,
  "Current password is required": ApiErrorCode.CURRENT_PASSWORD_REQUIRED,
  "New password is required": ApiErrorCode.NEW_PASSWORD_REQUIRED,
  "New password must be at least 6 characters long": ApiErrorCode.NEW_PASSWORD_MIN_LENGTH,
  "Refresh token is required": ApiErrorCode.REFRESH_TOKEN_REQUIRED,
  "Role is required": ApiErrorCode.ROLE_REQUIRED,
  "Role must be one of: SUPER_ADMIN, SCHOOL_ADMIN, INSTRUCTOR, USER": ApiErrorCode.ROLE_INVALID,

  // User Validation
  "First name is required": ApiErrorCode.FIRST_NAME_REQUIRED,
  "First name must be at least 2 characters long": ApiErrorCode.FIRST_NAME_MIN_LENGTH,
  "First name must not exceed 50 characters": ApiErrorCode.FIRST_NAME_MAX_LENGTH,
  "Last name is required": ApiErrorCode.LAST_NAME_REQUIRED,
  "Last name must be at least 2 characters long": ApiErrorCode.LAST_NAME_MIN_LENGTH,
  "Last name must not exceed 50 characters": ApiErrorCode.LAST_NAME_MAX_LENGTH,
  "Phone number is required": ApiErrorCode.PHONE_NUMBER_REQUIRED,
  "Phone number must be at least 10 characters long": ApiErrorCode.PHONE_NUMBER_MIN_LENGTH,
  '"phone" length must be at least 10 characters long': ApiErrorCode.PHONE_NUMBER_MIN_LENGTH,
  '"phoneNumber" length must be at least 10 characters long': ApiErrorCode.PHONE_NUMBER_MIN_LENGTH,
  "Phone number must not exceed 20 characters": ApiErrorCode.PHONE_NUMBER_MAX_LENGTH,
  '"phone" length must be less than or equal to 20 characters long': ApiErrorCode.PHONE_NUMBER_MAX_LENGTH,
  '"phoneNumber" length must be less than or equal to 20 characters long': ApiErrorCode.PHONE_NUMBER_MAX_LENGTH,
  "School ID is required": ApiErrorCode.SCHOOL_ID_REQUIRED,
  "School ID must be a valid UUID": ApiErrorCode.SCHOOL_ID_INVALID_UUID,
  "School ID is required. Your account is not associated with a school.": ApiErrorCode.SCHOOL_ID_NOT_ASSOCIATED,

  // School Validation
  "School name is required": ApiErrorCode.SCHOOL_NAME_REQUIRED,
  "School name must be at least 2 characters long": ApiErrorCode.SCHOOL_NAME_MIN_LENGTH,
  "School name must not exceed 100 characters": ApiErrorCode.SCHOOL_NAME_MAX_LENGTH,
  "Slug must be at least 2 characters long": ApiErrorCode.SLUG_MIN_LENGTH,
  "Slug must not exceed 50 characters": ApiErrorCode.SLUG_MAX_LENGTH,
  "Slug can only contain lowercase letters, numbers, and hyphens": ApiErrorCode.SLUG_INVALID,
  "Slug must be a valid string or empty": ApiErrorCode.SLUG_INVALID_FORMAT,
  "Disciplines are required": ApiErrorCode.DISCIPLINES_REQUIRED,
  "At least one discipline must be selected": ApiErrorCode.DISCIPLINES_MIN_SELECTION,
  "Open hours start must be in HH:MM or HH:MM:SS format": ApiErrorCode.OPEN_HOURS_INVALID_FORMAT,
  "Open hours end must be in HH:MM or HH:MM:SS format": ApiErrorCode.OPEN_HOURS_INVALID_FORMAT,
  "Logo must be a valid URL": ApiErrorCode.URL_INVALID,
  "Website must be a valid URL": ApiErrorCode.URL_INVALID,
  "Windguru URL must be a valid URL": ApiErrorCode.URL_INVALID,
  "Address must not exceed 500 characters": ApiErrorCode.ADDRESS_MAX_LENGTH,
  "Spot name must not exceed 100 characters": ApiErrorCode.SPOT_NAME_MAX_LENGTH,

  // Instructor Validation
  "Specialties are required": ApiErrorCode.SPECIALTIES_REQUIRED,
  "At least one specialty must be selected": ApiErrorCode.SPECIALTIES_MIN_SELECTION,
  "Languages are required": ApiErrorCode.LANGUAGES_REQUIRED,
  "At least one language must be selected": ApiErrorCode.LANGUAGES_MIN_SELECTION,
  "Avatar must be a valid URL": ApiErrorCode.AVATAR_INVALID_URL,
  "Certification must be at least 2 characters long": ApiErrorCode.CERTIFICATION_MIN_LENGTH,
  "Certification must not exceed 100 characters": ApiErrorCode.CERTIFICATION_MAX_LENGTH,
  "Notes must not exceed 1000 characters": ApiErrorCode.NOTES_MAX_LENGTH,
  "Hourly rate must be 0 or greater": ApiErrorCode.HOURLY_RATE_MIN,
  "Hourly rate must be a number": ApiErrorCode.HOURLY_RATE_INVALID,
  "Commission rate must be 0 or greater": ApiErrorCode.COMMISSION_RATE_MIN,
  "Commission rate must not exceed 100": ApiErrorCode.COMMISSION_RATE_MAX,
  "Commission rate must be a number": ApiErrorCode.COMMISSION_RATE_INVALID,

  // Student Validation
  "Student level is required": ApiErrorCode.STUDENT_LEVEL_REQUIRED,
  "Student level ID must be a valid UUID": ApiErrorCode.STUDENT_LEVEL_ID_INVALID_UUID,
  "Skill level is required": ApiErrorCode.SKILL_LEVEL_REQUIRED,
  "Skill level must be at least 1 character long": ApiErrorCode.SKILL_LEVEL_MIN_LENGTH,
  "Skill level must not exceed 50 characters": ApiErrorCode.SKILL_LEVEL_MAX_LENGTH,
  "Skill level cannot be empty": ApiErrorCode.SKILL_LEVEL_EMPTY,
  "Preferred disciplines are required": ApiErrorCode.PREFERRED_DISCIPLINES_REQUIRED,
  "At least one preferred discipline must be selected": ApiErrorCode.PREFERRED_DISCIPLINES_MIN_SELECTION,
  "Date of birth must be a valid date": ApiErrorCode.DATE_OF_BIRTH_INVALID,
  "Emergency contact name must not exceed 100 characters": ApiErrorCode.EMERGENCY_CONTACT_MAX_LENGTH,
  "Emergency phone must be at least 10 characters long": ApiErrorCode.EMERGENCY_PHONE_MIN_LENGTH,
  '"emergencyPhone" length must be at least 10 characters long': ApiErrorCode.EMERGENCY_PHONE_MIN_LENGTH,
  "Emergency phone must not exceed 20 characters": ApiErrorCode.EMERGENCY_PHONE_MAX_LENGTH,
  '"emergencyPhone" length must be less than or equal to 20 characters long': ApiErrorCode.EMERGENCY_PHONE_MAX_LENGTH,
  "Medical conditions must not exceed 1000 characters": ApiErrorCode.MEDICAL_CONDITIONS_MAX_LENGTH,
  "WhatsApp number is required": ApiErrorCode.WHATSAPP_NUMBER_REQUIRED,
  "WhatsApp number must be at least 10 characters long": ApiErrorCode.WHATSAPP_NUMBER_MIN_LENGTH,
  '"whatsappNumber" length must be at least 10 characters long': ApiErrorCode.WHATSAPP_NUMBER_MIN_LENGTH,
  "WhatsApp number must not exceed 20 characters": ApiErrorCode.WHATSAPP_NUMBER_MAX_LENGTH,
  '"whatsappNumber" length must be less than or equal to 20 characters long': ApiErrorCode.WHATSAPP_NUMBER_MAX_LENGTH,
  "Please indicate if you can swim": ApiErrorCode.CAN_SWIM_REQUIRED,
  "Swimming ability is required": ApiErrorCode.CAN_SWIM_REQUIRED,
  "Can swim must be true or false": ApiErrorCode.CAN_SWIM_INVALID,
  "Nationality must not exceed 100 characters": ApiErrorCode.NATIONALITY_MAX_LENGTH,
  "Weight must be a number": ApiErrorCode.WEIGHT_INVALID,
  "Weight must be at least 20 kg": ApiErrorCode.WEIGHT_MIN,
  "Weight must not exceed 200 kg": ApiErrorCode.WEIGHT_MAX,
  "Height must be a number": ApiErrorCode.HEIGHT_INVALID,
  "Height must be at least 50 cm": ApiErrorCode.HEIGHT_MIN,
  "Height must not exceed 250 cm": ApiErrorCode.HEIGHT_MAX,
  "Primary sport must be one of: surf, kitesurf, wingfoil, foil": ApiErrorCode.PRIMARY_SPORT_INVALID,
  "Riding background must not exceed 1000 characters": ApiErrorCode.RIDING_BACKGROUND_MAX_LENGTH,
  "Preferred language must not exceed 50 characters": ApiErrorCode.PREFERRED_LANGUAGE_MAX_LENGTH,

  // Discipline Validation
  "Name is required": ApiErrorCode.NAME_REQUIRED,
  "Name must be at least 2 characters long": ApiErrorCode.NAME_MIN_LENGTH,
  "Name must not exceed 50 characters": ApiErrorCode.NAME_MAX_LENGTH,
  // Note: "Name must not exceed 100 characters" used by Product Category - handled separately below
  "Display name is required": ApiErrorCode.DISPLAY_NAME_REQUIRED,
  "Display name must be at least 2 characters long": ApiErrorCode.DISPLAY_NAME_MIN_LENGTH,
  "Display name must not exceed 100 characters": ApiErrorCode.DISPLAY_NAME_MAX_LENGTH,
  "Description must not exceed 1000 characters": ApiErrorCode.DESCRIPTION_MAX_LENGTH,
  "Icon must not exceed 50 characters": ApiErrorCode.ICON_MAX_LENGTH,
  "Color must be a valid hex color code (e.g., #3B82F6)": ApiErrorCode.COLOR_INVALID_HEX,
  "Color must be a valid hex color code (e.g., #6B7280)": ApiErrorCode.COLOR_INVALID_HEX,
  "Sort order must be a number": ApiErrorCode.SORT_ORDER_INVALID,
  "Sort order must be an integer": ApiErrorCode.SORT_ORDER_INVALID,
  "Sort order must be 0 or greater": ApiErrorCode.SORT_ORDER_MIN,
  "Order position must be a number": ApiErrorCode.ORDER_POSITION_INVALID,
  "Order position must be an integer": ApiErrorCode.ORDER_POSITION_INVALID,
  "Order position must be 0 or greater": ApiErrorCode.ORDER_POSITION_MIN,

  // Product Category Validation 
  "Name must not exceed 100 characters": ApiErrorCode.CATEGORY_NAME_MAX_LENGTH,
  "Default max participants must be a number": ApiErrorCode.DEFAULT_MAX_PARTICIPANTS_INVALID,
  "Default max participants must be an integer": ApiErrorCode.DEFAULT_MAX_PARTICIPANTS_INVALID,
  "Default max participants must be at least 1": ApiErrorCode.DEFAULT_MAX_PARTICIPANTS_MIN,

  // Product Validation
  "Title is required": ApiErrorCode.TITLE_REQUIRED,
  "Title must be at least 2 characters long": ApiErrorCode.TITLE_MIN_LENGTH,
  "Title must not exceed 255 characters": ApiErrorCode.TITLE_MAX_LENGTH,
  "Category ID is required": ApiErrorCode.CATEGORY_ID_REQUIRED,
  "Category ID must be a valid UUID": ApiErrorCode.CATEGORY_ID_INVALID_UUID,
  "Discipline ID must be a valid UUID": ApiErrorCode.DISCIPLINE_ID_INVALID_UUID,
  "Price is required": ApiErrorCode.PRICE_REQUIRED,
  "Price must be 0 or greater": ApiErrorCode.PRICE_MIN,
  "Price must be a number": ApiErrorCode.PRICE_INVALID,
  "Duration must be a number": ApiErrorCode.DURATION_INVALID,
  "Duration must be 0 or greater": ApiErrorCode.DURATION_MIN,
  "Max participants must be a number": ApiErrorCode.MAX_PARTICIPANTS_INVALID,
  "Max participants must be an integer": ApiErrorCode.MAX_PARTICIPANTS_INVALID,
  "Max participants must be at least 1": ApiErrorCode.MAX_PARTICIPANTS_MIN,
  "Price type must be one of: per_person, per_couple, fixed": ApiErrorCode.PRICE_TYPE_INVALID,
  "Description must not exceed 500 characters": ApiErrorCode.PRODUCT_DESCRIPTION_MAX_LENGTH,
  "Note must not exceed 1000 characters": ApiErrorCode.PRODUCT_NOTE_MAX_LENGTH,

  // Pagination & Search Validation
  "Page must be a number": ApiErrorCode.PAGE_INVALID,
  "Page must be an integer": ApiErrorCode.PAGE_INVALID,
  "Page must be at least 1": ApiErrorCode.PAGE_MIN,
  "Limit must be a number": ApiErrorCode.LIMIT_INVALID,
  "Limit must be an integer": ApiErrorCode.LIMIT_INVALID,
  "Limit must be at least 1": ApiErrorCode.LIMIT_MIN,
  "Limit must not exceed 100": ApiErrorCode.LIMIT_MAX,
  "Search query is required": ApiErrorCode.SEARCH_QUERY_REQUIRED,
  "Search query must be at least 1 character long": ApiErrorCode.SEARCH_QUERY_MIN_LENGTH,
  "Search query must not exceed 100 characters": ApiErrorCode.SEARCH_QUERY_MAX_LENGTH,

  // Business Logic Errors
  "Instructor already has a lesson scheduled at this time. Please choose a different time slot.": ApiErrorCode.INSTRUCTOR_LESSON_CONFLICT,
  "Instructor already has a lesson": ApiErrorCode.INSTRUCTOR_ALREADY_HAS_LESSON,
  "School is closed on the selected date": ApiErrorCode.SCHOOL_CLOSED_DATE,
  "School is closed on the selected date. Cannot create lessons.": ApiErrorCode.SCHOOL_CLOSED_CANNOT_CREATE,
  "Instructor not available for the requested time": ApiErrorCode.INSTRUCTOR_NOT_AVAILABLE,
  "Requested time overlaps with another lesson": ApiErrorCode.LESSON_TIME_OVERLAP,
  "Invalid student_id: student not found in this school or is inactive. Select a student from the Students list.": ApiErrorCode.INVALID_STUDENT_ID,
  "School with this slug already exists": ApiErrorCode.SCHOOL_SLUG_EXISTS,
  "Cannot create booking: The following student(s) must have a skill level set:": ApiErrorCode.BOOKING_STUDENTS_SKILL_LEVEL_REQUIRED,
  "No available booked hours for this student. Please contact the school to update the booking.": ApiErrorCode.NO_AVAILABLE_BOOKED_HOURS,
  "You are not authorized by this school to edit lessons.": ApiErrorCode.INSTRUCTOR_EDIT_NOT_AUTHORIZED,

  // Resource Errors
  "Lesson ID is required": ApiErrorCode.LESSON_ID_REQUIRED,
  "Discipline ID is required": ApiErrorCode.DISCIPLINE_ID_REQUIRED,
  "User ID is required": ApiErrorCode.USER_ID_REQUIRED,
  "School not found": ApiErrorCode.SCHOOL_NOT_FOUND,
  "Lesson not found": ApiErrorCode.LESSON_NOT_FOUND,
  "Student not found": ApiErrorCode.STUDENT_NOT_FOUND,
  "Discipline not found": ApiErrorCode.DISCIPLINE_NOT_FOUND,
  "Student level not found": ApiErrorCode.STUDENT_LEVEL_NOT_FOUND,
  "Product not found": ApiErrorCode.PRODUCT_NOT_FOUND,
  "Product category not found": ApiErrorCode.PRODUCT_CATEGORY_NOT_FOUND,
  "User not found": ApiErrorCode.USER_NOT_FOUND,

  // Authorization Errors
  "Authentication required": ApiErrorCode.AUTHENTICATION_REQUIRED,
  "Access denied": ApiErrorCode.ACCESS_DENIED,
  "User not associated with any school": ApiErrorCode.USER_NOT_ASSOCIATED_SCHOOL,
  "User not authenticated": ApiErrorCode.USER_NOT_AUTHENTICATED,

  // System Errors
  "Validation failed": ApiErrorCode.VALIDATION_FAILED,
  "Internal server error": ApiErrorCode.INTERNAL_SERVER_ERROR,
  "date query required": ApiErrorCode.DATE_QUERY_REQUIRED,
};

export function getErrorCodeFromMessage(message: string): ApiErrorCode | undefined {
  return ERROR_MESSAGE_TO_CODE[message];
}

